### ISSUE TITLE
JS not included in dev?

### ISSUE THREAD

**Issue by mandrasch** [holger1411/11straps#23]
Hey,

thanks very much for providing this starter!

I started with the dev version and seems that JS is missing (I tried bootstrapp navbar with toggle/collapse).

Best regards,
Matthias

**Comment by holger1411** [comment]
Sorry for my late reply! Don´t recognized that someone is actually using this ;-)

The JS files are there in the /js folder. But the default template (https://github.com/holger1411/11straps/blob/main/src/_includes/layouts/base.njk) dont load it by default.
I just don´t need any JS on the demo site here: https://11straps.com/

Just add this:
<script src="js/bootstrap.bundle.min.js"></script> to the base template and it should work than

**Comment by holger1411** [comment]
I add a sample page (including a sample template called default.njk) and a sample blog with sample posts and a sample post view template. All pulling in the JS file the proper way now. 
You can use this as starting point with full Bootstrap JS support.
Closing this. Thx @mandrasch again for bringing up this issue
