### ISSUE TITLE
Suggestion: Use relative links for assets

### ISSUE THREAD

**Issue by mandrasch** [holger1411/11straps#24]
Currently this boilerplate uses

`<link rel="stylesheet" href="css/theme.css">`

As far as I understand 11ty, you can use relative urls. This supports the use case of having an 11ty site on a subdirectory, e.g. https://pages.github.com/user/my-11tystraps-project/

So a better way could be:

`<link rel="stylesheet" href="{{ "css/themes" | url }}"">`

Docs: https://www.11ty.dev/docs/filters/url/

If you agree, I could also (of course) send a PR to change this. 

Thanks in advance!

Best regards!
PS: Disclaimer - I'm a 11ty newbie :)
PPS: Also a subpage like "about.njk" would be cool in this boilerplate to show the power of 11ty.

**Comment by holger1411** [comment]
Feel free to open up a PR!
I´am also a total 11ty noob

**Comment by holger1411** [comment]
Was changed. I replaced all links to assets like JS, img, css etc with the 11ty URL filter.
Closing this. Thx @mandrasch for bring this up
