### ISSUE TITLE
npm run watch not working on windows

### ISSUE THREAD

**Issue by jpkeisala** [holger1411/11straps#84]
> rm -rf dev/*

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 11strap@0.7.0 clean: `rm -rf dev/*`
npm ERR! Exit status 1

**Comment by holger1411** [comment]
Argh, yes. the "rm" command must be replaced by "del" on win OS.
Maybe not a good practice from my side.
Will try to replace it by a OS agnostic approach.
